### ISSUE TITLE
wxpython.org is down

### ISSUE THREAD

**Issue by demmerichs** [wxWidgets/Phoenix#2474] opened 2023-11-06 19:45 UTC
Your website is currently down!
See also here https://www.saashub.com/wxpython-status

**Comment by jmoraleda** [comment] 2023-11-07 00:05
I confirm that. It has been down since at least yesterday.

**Comment by noeldiviney** [comment] 2023-11-07 00:29
I also confirm. I get timeouts here in Melbourne Australia. I can ping the ip address sucessfully, however.
Noel

**Comment by reticulatus** [comment] 2023-11-07 21:34
It's working for me now.

**Comment by jmoraleda** [comment] 2023-11-07 22:37
Confirmed. It is working for me too. I think we can close this issue.

**Closed** 2023-11-07 23:21 UTC

**Comment by badabing2005** [comment] 2026-05-21 19:33
This an issue again
