### ISSUE TITLE
DataViewModel Cleared() does not redraw view on Linux GTK

### ISSUE THREAD

**Issue by Carbenium** [wxWidgets/Phoenix#824] opened 2018-04-20 13:06 UTC
**Operating system**: Linux Mint 18.3
**wxPython version**: 4.0.1
**Stock or custom build**: stock
**Python version**: 3.5.2
**Stock or custom build**: stock

**Description of the problem**:
Same issue as in https://trac.wxwidgets.org/ticket/16601
Calling `PyDataViewModel.Cleared()` clears the `DataViewCtrl` but does not update it with the current model data. 

```python
    def on_click_add_(self, e):
        step = Step("Step 1", [Param("Step 1", "Key1", "2"), Param("Step 1", "Key2", "3")])
        self.model.steps.append(step)
        self.model.Cleared()
```

**Comment by RobinD42** [comment] 2018-05-09 01:41
I'm not sure I'm following everything in that ticket. With `Cleared` you are telling the model that all items have been removed. If there are new items after that shouldn't you be calling `ItemsAdded` to let the framework know about them?

**Comment by Nutznieser** [comment] 2018-08-05 11:36
The problem is that there is a different behavior in Windows vs. Linux.

In Windows `self.model.Cleared()` does exactly what is described in the documentation: `Called to inform the model that all data has been cleared. The control will reread the data from the model again.` In Linux the last step of this description is omitted. And so the control will NOT reread the data.

I don't know how to update a model according the methods like `ItemsAdded, ...` if you have a complex tree with many changes or if you want loading an complete different tree in the model.

In my code I solve this problem in that way: I do removing the old model completely and associate a new model (with the new data) to the `DataViewCtrl` (see code below). It works. But I'am not sure if that is the right way?

```Python
def UpdateModel(self, model):
    if self.model:
        # Clear all selections before update the model. Otherwise 'old'
        # selections can cause inpredictable errors!
        self.UnselectAll()

        # Remove old model
        del self.model

    # Associate new model
    self.model = model
    self.AssociateModel(self.model)
    self.model.DecRef()
```

**Comment by jmoraleda** [comment] 2019-03-31 22:59
This problem is still present in the latest source code. In summary, under GTK there is no easy way to change the model in a complex way and then tell the control to redraw itself.

**Comment by jmoraleda** [comment] 2020-12-07 03:33
I just tested this, and I can confirm this issue has been fixed upstream in wxWidgets as of commit https://github.com/stahta01/wxwidgets_master_fork/commit/5403ec4e086c4fbc3d9ee9bf4b38964a48357826
@RobinD42 Feel free to close this issue.

**Closed** 2020-12-19 00:03 UTC
Labels: awaiting-response, wxWidgets
