### ISSUE TITLE
wx.Button.SetBitmapPosition does not work with GTK3

### ISSUE THREAD

**Issue by jaknel** [wxWidgets/Phoenix#606] opened 2017-11-09 19:05 UTC
**Operating system**:  Ubuntu 16.04.3 LTS (Xenial Xerus)
**wxPython version**:   Python 2.7.12 on linux2, wxPython 4.0.0rc1 gtk3  (phoenix)
**Stock or custom build**: custom  
**Python version**: Python 2.7.12
**Stock or custom build**: stock

**Description of the problem**:  
https://wxpython.org/Phoenix/docs/html/wx.AnyButton.html#wx.AnyButton.SetBitmapPosition

button.SetBitmap(bmp, dir=wx.TOP) and button.SetBitmapPosition(wx.TOP) fail to change the orientation of the Bitmap on a wx.Button that also has a label set.

http://i.imgur.com/uMz9myl.png

A  GTK2 build of wxpython (Python 2.7.12 on linux2, wxPython 4.0.0rc1 gtk2 (phoenix)) on the same linux machine behaves as expected, as does running the application on OS X  (Python 2.7.12 on darwin, wxPython 4.0.0rc1.dev3477+0aa026a osx-cocoa (phoenix))
OSX Screenshot: https://i.imgur.com/CnTSvpT.png

```python
import wx

app = wx.App()

frm = wx.Frame(None, title="Hello World!", size=(400, 275))
pnl = wx.Panel(frm)
pnl.BackgroundColour = 'sky blue'

sizer = wx.BoxSizer(wx.HORIZONTAL)

btn = wx.Button(pnl)

btn.SetLabel("Test")

bitmap = wx.Bitmap(50, 50)
dc = wx.MemoryDC()
dc.SelectObject(bitmap)
dc.Clear()
dc.SetBrush(wx.Brush(wx.Colour(255, 105, 180), wx.SOLID))
dc.DrawRectangle(0, 0, 50, 50)
dc.DrawText("Img", 5, 5)
dc.SelectObject(wx.NullBitmap)

btn.SetBitmap(bitmap)
btn.SetBitmapPosition(wx.TOP)
sizer.Add(btn, flag=wx.EXPAND)

pnl.SetSizerAndFit(sizer)

frm.Show()
app.MainLoop()

```

I've included C code directly using GTK3 to show the library behaving as expected.
```c
#include <gtk/gtk.h>
 
//gcc `pkg-config --cflags gtk+-3.0` -o gtk_3_sample gtk_3_sample.c `pkg-config --libs gtk+-3.0`
 
static void
activate(GtkApplication* app,
     gpointer user_data)
{
  GtkWidget *window;
 
  window = gtk_application_window_new(app);
  gtk_window_set_title(GTK_WINDOW(window), "window");
  gtk_window_set_default_size(GTK_WINDOW(window), 200, 200);
 
  GtkWidget *btn;
  btn = gtk_button_new_with_label("test");
 
  gtk_container_add(GTK_CONTAINER(window), btn);
  GtkWidget *image;
  image = gtk_image_new_from_icon_name("Test", GTK_ICON_SIZE_BUTTON);
  gtk_button_set_image(GTK_BUTTON(btn), image);
  gtk_button_set_image_position(GTK_BUTTON(btn), GTK_POS_TOP);
 
  gtk_widget_show_all(window);
 
 
}
 
int
main(int argc,
     char **argv)
{
  printf("GTK Version: %d.%d.%d\n", gtk_get_major_version(),
     gtk_get_minor_version(),
     gtk_get_micro_version());
  GtkApplication *app;
  int status;
 
  app = gtk_application_new("org.gtk.example", G_APPLICATION_FLAGS_NONE);
  g_signal_connect(app, "activate", G_CALLBACK (activate), NULL);
  status = g_application_run(G_APPLICATION(app), argc, argv);
  g_object_unref(app);
 
  return status;
}
```

**Comment by swt2c** [comment] 2017-11-10 01:19
I don't see any bitmap with your test code, either with gtk2 or gtk3.

**Comment by jaknel** [comment] 2017-11-10 14:12
Sorry, on my system an unintialized wx.Bitmap shows up as a black box.  I've updated my python code in the initial comment to draw a pink Bitmap containing the text "Img".

**Comment by RobinD42** [comment] 2017-11-18 00:29
wxPython isn't doing anything special here, so this should be a wxWidgets issue.  Please repost the bug report at trac.wxwidgets.org and leave a link to it here for tracking.

**Comment by swt2c** [comment] 2017-11-18 01:56
I have a hunch about what might need to be fixed on the wxWidgets side, but I still can't reproduce the problem.  @jaknel thanks for updating your reproducer, but I still don't see any bitmap on my system.  Could be a separate bug I suppose.

**Comment by RobinD42** [comment] 2017-11-18 05:05
Perhaps a global GTK or GNOME preference?  I don't see the image on the button on my linux VM either.

**Comment by jaknel** [comment] 2017-11-22 18:34
I've submitted a ticket for wxWidgets proper  

https://trac.wxwidgets.org/ticket/18004

The issue is reproducible on my system using the bundled wxWidgets/samples/widgets application.

**Comment by swt2c** [comment] 2017-11-23 01:18
@RobinD42 this has been fixed upstream, can you please update the wxWidgets commit?

**Closed** 2017-11-23 18:51 UTC
Labels: wxWidgets
