### ISSUE TITLE
AGW AUI crash on detaching pane with Python 3.9.1

### ISSUE THREAD

**Issue by lallulli** [wxWidgets/Phoenix#1885] opened 2021-01-02 14:31 UTC
**Operating system**: Windows 10 x64
**wxPython version & source**: wxPython 4.1.1 (PyPI wheel)
**Python version & source**: CPython 3.9.1 32 bit (python.org)

**Description of the problem**:

I experience a crash when running AGW AUI sample code from official documentation: https://wxpython.org/Phoenix/docs/html/wx.lib.agw.aui.html

When I drag "Pane Number One" or "Pane Number Two", as soon as I detach the pane from the window side, my application crashes without any error messages.

It works fine in Python 3.8.7.

**Comment by kdschlosser** [comment] 2021-01-11 21:27
duplicate of #1881

**Closed** 2021-01-18 22:44 UTC
