### ISSUE TITLE
Demo fails because distutils package has been removed as of Python 3.12 PEP 362

### ISSUE THREAD

**Issue by egoZentric** [wxWidgets/Phoenix#2523] opened 2024-02-05 01:08 UTC
CRITICAL ! Demo will never run.

Demo will no longer run as vanilla out-of-the-box install with python 3.12.1 and wxPython 4.2.1 on Win10

Traceback (most recent call last):
  File "C:\Users\* *\wxPython-demo-4.2.1\demo\demo.py", line 3, in <module>
    import Main
  File "C:\Users\* *\wxPython-demo-4.2.1\demo\Main.py", line 59, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

**Comment by swt2c** [comment] 2024-02-05 01:11
Duplicate of #2519

**Closed by swt2c** 2024-02-05 01:11 UTC

**Comment by egoZentric** [comment] 2024-02-05 01:14
... BUT #2519 is also closed !
so wher is the OPEN issue if i may ask ?

**Comment by swt2c** [comment] 2024-02-05 01:18
It has been fixed in git so the issue is closed.  It just hasn't been released yet.

**Comment by egoZentric** [comment] 2024-02-05 01:24
SOLVED.

https://github.com/wxWidgets/Phoenix/pull/2520

https://github.com/wxWidgets/Phoenix/commit/7e2c7d69c9a71c77b3fb2e0f3d55ccbc7eab6742
