### ISSUE TITLE
wx.ListCtrl: crash when trying to set weight on list item

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#525] opened 2017-09-10 22:42 UTC
**Operating system**: Windows 10 x64
**wxPython version**: 4.0.0b1
**Stock or custom build**: stock
**Python version**: 3.6.1
**Stock or custom build**: stock

**Description of the problem**:
In wxPython 2.8/3.0, I was able to to perform a SetItemFont() on a list item in wx.ListCtrl. I am still able to do this, however, when first modifying the font by setting a weight to bold, the program crashes

```
import wx


########################################################################
class MyForm(wx.Frame):
    # ----------------------------------------------------------------------
    def __init__(self):
        wx.Frame.__init__(self, None, wx.ID_ANY, "List Control Tutorial")

        # Add a panel so it looks the correct on all platforms
        panel = wx.Panel(self, wx.ID_ANY)
        self.index = 0

        self.list_ctrl = wx.ListCtrl(panel, size=(-1, 100),
                                     style=wx.LC_REPORT
                                           | wx.BORDER_SUNKEN
                                     )
        self.list_ctrl.InsertColumn(0, 'Subject')
        self.list_ctrl.InsertColumn(1, 'Due')
        self.list_ctrl.InsertColumn(2, 'Location', width=125)

        btn = wx.Button(panel, label="Add Line")
        btn.Bind(wx.EVT_BUTTON, self.add_line)

        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.list_ctrl, 0, wx.ALL | wx.EXPAND, 5)
        sizer.Add(btn, 0, wx.ALL | wx.CENTER, 5)
        panel.SetSizer(sizer)

    # ----------------------------------------------------------------------
    def add_line(self, event):
        line = "Line %s" % self.index
        self.list_ctrl.InsertStringItem(self.index, line)
        self.list_ctrl.SetStringItem(self.index, 1, "01/19/2010")
        self.list_ctrl.SetStringItem(self.index, 2, "USA")

        font = (self.GetClassDefaultAttributes()).font
        #font.SetWeight(wx.FONTWEIGHT_BOLD)
        self.list_ctrl.SetItemFont(self.index, font)
        
        self.index += 1


# ----------------------------------------------------------------------
# Run the program
if __name__ == "__main__":
    app = wx.App(False)
    frame = MyForm()
    frame.Show()
    app.MainLoop()
```

Code is from a random minimal example that I found online. Remove the comment on this line: `font.SetWeight(wx.FONTWEIGHT_BOLD)`. The code runs fine with python 2.7 / wxPython 3.0, however crashes on python 3.6 / wxPython 4.0.0b1.

I have only tried modifying the font to be bold - I haven't tried any other modifications yet (italics, color changes, etc)

**Comment by blitzmann** [comment] 2017-09-11 00:32
Looks like any font manipulation. font.SetUnderlined() and SetStrikethrough() also doesn't work, among others

**Comment by RobinD42** [comment] 2017-09-12 22:55
I'll take a closer look later, but it looks to me like the problem is probably that the object returned by `GetClassDefaultAttributes` is being garbage collected since a reference to it is not being saved, and so the font object within that C++ structure no longer exists either, and so calling it's methods leads to a crash.  There may have been an extra reference somewhere in Classic, or perhaps an implicit copy or something that allowed this to work, or it may have just been luck.

Either way, it is easy to do an explicit copy yourself and avoid the problem.  Try getting the font like this:

```python
font = wx.Font(self.GetClassDefaultAttributes().font)
```

**Comment by blitzmann** [comment] 2017-09-13 03:13
@RobinD42 works great! Thanks for all the hard work :)

Just a question - how hard is it to figure this out? I'm not a C / C++ developer, but I would be interested in knowing how to diagnose and troubleshoot the issue, such as what IDE can be used, how to trace a python issue into the lower level code, etc. Is there a guide somewhere to help get development up and running specifically for wxPython?

**Comment by RobinD42** [comment] 2017-09-13 16:25
With some C/C++ skills to build upon, it's not super difficult to figure out. The main hurdle is that there are lots of pieces and there needs to be a good understanding of what they do, how they work and how they fit together. The other part of it is basically time.  Time to get experience with working on the code, to get familiar with all the pieces, etc.

**Comment by RobinD42** [comment] 2017-09-28 00:41
Not sure anything else can be done about this. Closing for now.

**Closed by RobinD42** 2017-09-28 00:41 UTC
