### ISSUE TITLE
wxPanel not inheriting size of parent Frame

### ISSUE THREAD

**Issue by blitzmann** [wxWidgets/Phoenix#1185] opened 2019-03-17 23:55 UTC
**Operating system**: Windows 10 
**wxPython version & source**:    4.0.3
**Python version & source**:           3.6
**Description of the problem**:

I have a Frame with a panel in it, that has a HyperTreeList (HTL) on it. I recently ran into an issue where I wanted to set the size of the HTL columns to the max of their content. I was running into an issue with the columns instead being calculated as 16 pixels wide.

Further investigation shows that the column resize calculation relied on `GetClientSize`, which was only `16x16` for the tree ctrl, and `20x20` for the panel. I had to set a manual size for the panel in order for the HTL to calculate columns correctly.

I'm wondering why that is. Why doesn't the panel default to it's parent Frame size? Below is an example of the problem, which is rectified as soon as you put a size on panel (something large like `(1000,1000)`)

```python
import wx
import wx.lib.agw.hypertreelist


class ItemParams(wx.Panel):
    def __init__(self, parent):
        # Had to manually set the size here, otherwise column widths couldn't be calculated correctly. See #1878
        wx.Panel.__init__(self, parent)
        mainSizer = wx.BoxSizer(wx.VERTICAL)

        self.tree = wx.lib.agw.hypertreelist.HyperTreeList(self, wx.ID_ANY, agwStyle=wx.TR_HIDE_ROOT | wx.TR_NO_LINES | wx.TR_FULL_ROW_HIGHLIGHT | wx.TR_HAS_BUTTONS)
        self.tree.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_WINDOW))

        self.tree.AddColumn("Col 1")
        self.tree.AddColumn("Col 2")

        root = self.tree.AddRoot("The Root Item")
        for x in range(5):
            item = self.tree.AppendItem(root, "Data")
            self.tree.SetItemText(item, "More Data", 1)

        mainSizer.Add(self.tree, 1, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(mainSizer)
        self.Layout()

        print(self.GetClientSize())
        print(self.tree.GetClientSize())
        for i in range(self.tree.GetMainWindow().GetColumnCount()):
            self.tree.SetColumnWidth(i, wx.LIST_AUTOSIZE)


if __name__ == "__main__":

    class Frame(wx.Frame):
        def __init__(self, ):

            super().__init__(None, title="Test Window", size=(500, 500))

            if 'wxMSW' in wx.PlatformInfo:
                color = wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNFACE)
                self.SetBackgroundColour(color)

            main_sizer = wx.BoxSizer(wx.HORIZONTAL)

            panel = ItemParams(self)

            main_sizer.Add(panel, 1, wx.EXPAND | wx.ALL, 2)

            self.SetSizer(main_sizer)
            self.Layout()

    app = wx.App(redirect=False)   # Error messages go to popup window
    top = Frame()
    top.Show()
    app.MainLoop()

```

![image](https://user-images.githubusercontent.com/3904767/54499990-8c040200-48ee-11e9-9bb4-213a22fa5d14.png)

**Comment by ricpol** [comment] 2019-04-17 19:54
This is not a bug. It's just that "SetColumnWidth" is asking for the panel size *before* the panel is assigned to the parent window. 
This works as expected: 

```python 
class ItemParams(wx.Panel):
    def __init__(self, parent):
        wx.Panel.__init__(self, parent)
        self.tree = wx.lib.agw.hypertreelist.HyperTreeList(self, wx.ID_ANY, agwStyle=wx.TR_HIDE_ROOT)
        self.tree.AddColumn("Col 1")
        self.tree.AddColumn("Col 2")
        root = self.tree.AddRoot("The Root Item")
        for x in range(5):
            item = self.tree.AppendItem(root, "Data")
            self.tree.SetItemText(item, "More Data", 1)
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        mainSizer.Add(self.tree, 1, wx.ALL|wx.EXPAND, 0)
        self.SetSizer(mainSizer)
        # self.Layout() means nothing at this point...

    def fix_column_size(self):
        print(self.GetClientSize())
        print(self.tree.GetClientSize())
        for i in range(self.tree.GetMainWindow().GetColumnCount()):
            self.tree.SetColumnWidth(i, wx.LIST_AUTOSIZE)

class Frame(wx.Frame):
    def __init__(self):
        super().__init__(None, title="Test Window", size=(500, 500))
        panel = ItemParams(self)
        main_sizer = wx.BoxSizer(wx.HORIZONTAL)
        main_sizer.Add(panel, 1, wx.EXPAND|wx.ALL, 2)
        self.SetSizer(main_sizer)
        self.Layout() # or even self.Fit()
        # now SetColumnWidth has all the info it needs to calculate columns' width
        panel.fix_column_size() 

if __name__ == "__main__":
    app = wx.App(redirect=False)
    Frame().Show()
    app.MainLoop()
```

**Closed** 2019-04-18 02:03 UTC
