### ISSUE TITLE
Follow up to #782 - update to wx.lib.pubsub

### ISSUE THREAD

**Issue by david-hughes** [wxWidgets/Phoenix#797] opened 2018-03-22 10:53 UTC
#782 has been closed so I'm not sure if adding a comment to it would be seen.

The change is beneficial in that wx.lib.pubsub will now always be the latest version of PyPubSub but unfortunately it still doesn't work with PyInstaller, the reason being that it doesn't seem to be able to distinguish between the import of the local pubsub in wx.lib and the external pubsub that the local pubsub imports. I've tried the various import-hook trickery that PyInstaller provides but without success.

The simple solution is for the application to import the external pubsub - which will always be there - directly instead of importing wx.lib.pubsub. Do you think it is worth (me) adding a note to this effect in the docstring within wx.lib.pubsub.\_\_init\_\_.py?

**Comment by mesalu** [comment] 2018-03-22 19:58
The changes in #782 were merged in with #792.

I'm quite out of practice with PyInstaller but shouldn't it follow imports through `wx.lib.pubsub` through to the external `pypubsub` dependency now, or at least with the import hooks you mentioned?

Have you tried using PyInstaller with a brand new build of Phoenix?

**Comment by david-hughes** [comment] 2018-03-23 10:30
Yes I should have said I'm running wx version 4.0.2a1.dev3708+62669d0 msw (phoenix) that contains the new pubsub version 4. 

Having found an import for pubsub which is actually wx.lib.pubsub, when it in turn imports the external pubsub PyInstaller doees not detect it is a different import and seems to behave as if the import is already satisfied. I couldn't configure an import hook to persuade it otherwise - but that may well be down to my own ignorance.

**Comment by mesalu** [comment] 2018-03-23 20:46
I haven't been able to dig into it very far yet but I suspect that the cause is due to this file:
https://github.com/pyinstaller/pyinstaller/blob/07ab024c395619e7a220628f99173ca64e044d88/PyInstaller/hooks/hook-wx.lib.pubsub.py

It looks like pyinstaller int he past has taken specific action to ensure that`wx.lib.pubsub` was correctly hooked, and that we just knife edge rolled them.

@RobinD42, thoughts?

**Comment by mesalu** [comment] 2018-03-23 20:54
I'm not well versed in PyInstaller hooks, but I don't see anything that would explicitly break the module graph tracing to the external `PyPubSub` in that hook, it just looks to add modules that are no longer there.

**Comment by david-hughes** [comment] 2018-03-24 11:53
Version 3.3.0 of pubsub supported two different message formats, and the code for the appropriate type was dynamically imported when wx.lib.pubsub itself was first imported. This caused great problems to PyInstaller and PyInstaller/hooks/hook-wx.lib.pubsub.py attempted to resolve these.  But looking at the open Issues there have been several, so far unsuccessful attempts to complete it going back several years, in particular, issues #1367, #1530, #2215 and #2233.

Pubsub version 4.0.0 only supports a single message format and so hook-wx.lib.pubsub.py is no longer needed in its present form. I have removed it from my local Python installation but that has had no effect on the current problem of getting PyInstaller to differentiate between the local wx.lib.pubsub and the external pubsub that actually contains pubsub version 4. In the attempts to resolve this problem that I referrred to earlier, I tried to do it via a replacement version of hook-wx.lib.pubsub.py but without success.

**Comment by mesalu** [comment] 2018-08-02 20:45
Looks like we're sticking with an integrated pubsub that is explicitly deprecated. (Sorry PyInstaller users. :\ ) 
Eventually, likely after py2, we'll deprecate the use of wx.lib.pubsub and encourage the use of using pypubsub independently.

**Closed by mesalu** 2018-08-02 20:45 UTC
