### ISSUE TITLE
SButton background colour is incorrect under GTK3

### ISSUE THREAD

**Issue by carandraug** [wxWidgets/Phoenix#1715] opened 2020-07-03 18:19 UTC
**Operating system**: Linux
**wxPython version & source**: 4.1.0 gtk3 (phoenix) wxWidgets 3.1.4 from PyPI
**Python version & source**: Python 3.7 from Debian repos

`SButton` is painted on top of a rectangular window which is set to be the same colour as the parent background.  However, at least under GTK3 this is wrong:

```
import wx
import wx.lib.agw.shapedbutton

app = wx.App()

frame = wx.Frame(None, size=(100, 100))
button = wx.lib.agw.shapedbutton.SButton(frame, size=(50,100))
sizer = wx.BoxSizer()
sizer.Add(button)
frame.SetSizer(sizer)
frame.Show()

app.MainLoop()
```

which with the default Gnome theme creates:

![sbutton-bug](https://user-images.githubusercontent.com/916140/86491051-6f990c80-bd61-11ea-936c-baf015b07538.png)

The background colours are different (it becomes much more noticeable when there's multiple such buttons on a grid). I've measured them with a colour pick and the button background is `(241, 240, 238)` and the panel background colour is `(246, 245, 244)`.

Getting the background colour from the panel does report `(241, 240, 238)` so there may be an issue somewhere else. However, since it is possible for the background to be a gradient or an image, the background of the `SButton` window should probably be transparent.

**Comment by Metallicow** [comment] 2020-07-06 05:43
You might be confusing my ShapedBitmapButton implementation with the agw.ShapedButton. I don't recall ShapedButton had gradient or image options as it is a bit dated. Tho the background color *should match the parent widget.

**Comment by carandraug** [comment] 2020-07-06 13:05
> You might be confusing my ShapedBitmapButton implementation with the agw.ShapedButton.

I don't think so. I even have a minimal code example to reproduce the issue and it uses `agw.shapedbutton.SButton`

**Comment by Metallicow** [comment] 2020-07-06 19:01
hmmm.... this is in the OnPaint method... something funny must be going on or with the theme maybe...

```python
        # The DC Background *Must* Be The Same As The Parent Background Colour,
        # In Order To Hide The Fact That Our "Shaped" Button Is Still Constructed
        # Over A Rectangular Window
        brush = wx.Brush(self.GetParent().GetBackgroundColour())
```

@carandraug Could you test a sample image with my ShapedBitmapButton implementation and see if you have the same issue on your linux flavor.
https://github.com/Metallicow/MCOW

...If mine doesn't have the same problem, you might look at the differences in how it is dealing with handling the background color. Otherwise it might be OS theme specific issue...

**Comment by carandraug** [comment] 2020-07-06 19:35
> hmmm.... this is in the OnPaint method... something funny must be going on or with the theme maybe...

As I mentioned on the first post, there must be an issue on that `GetBackgroundColour`. I have measured it and it reports something different. Despite that issue, which I think is separate, the idea of picking the parent background colour can lead to problems with some themes that may not have a single background colour so it would be better to have it transparent instead of painting with the supposed background colour.

> @carandraug Could you test a sample image with my ShapedBitmapButton implementation and see if you have the same issue on your linux flavor.

Sure. Can you give me a minimal code to test it. I have never used MCOW before.

**Comment by Metallicow** [comment] 2020-07-06 19:48
There is a demo in the repo that should work. You might have to change where the import is, but the MCOW package can be dropped right in wx.lib directory.

**Comment by carandraug** [comment] 2020-07-06 21:53
The MCOW package has the same problem. I just ran `python3 MCOW/Demos/ShapedBitmapButton/ShapedBitmapButton.py` and the slighly darker grey on the button also appears there. Here's a screenshoot:

![mcow](https://user-images.githubusercontent.com/916140/86651111-2bb13c00-bfdb-11ea-8994-4780a2f792ee.png)

For what is worth, the wxWidgets issue is at https://trac.wxwidgets.org/ticket/18811

**Comment by Metallicow** [comment] 2020-07-07 05:12
ummmm. Ok. I see the wxWidgets Issue. I haven't had time to update my widget, but both could benefit from the new DC drawing classes. Maybe that might be able to fix it or not... It takes time to update and test the widgets. The GCDC or GC stuff works with transparency better on some OS but may not work with all....

**Comment by Metallicow** [comment] 2020-07-07 06:51
Here is a Py2/3 sample that works for testing with a proper panel.

<details>
    <summary>Collapsible Content - Click to expand</summary>

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

""""""

# Imports.--------------------------------------------------------------------
# -Python Imports.
import os
import sys

# -wxPython Imports.
import wx
import wx.lib.agw.shapedbutton

class MyPanel(wx.Panel):
    """"""
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.BORDER_SUNKEN, name='panel'):
        """"""
        wx.Panel.__init__(self, parent, id, pos, size, style, name)

        # ... Add widget here
        button = wx.lib.agw.shapedbutton.SButton(self, size=(50, 100))

        sizer = wx.BoxSizer()
        sizer.Add(button)

class MyFrame(wx.Frame):
    """"""
    def __init__(self, parent, id=wx.ID_ANY, title=wx.EmptyString,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.DEFAULT_FRAME_STYLE, name='frame'):
        """"""
        wx.Frame.__init__(self, parent, id, title, pos, size, style, name)
        global gMainWin
        gMainWin = self
        wxVER = 'wxPython %s' % wx.version()
        pyVER = 'python %d.%d.%d.%s' % sys.version_info[0:4]
        versionInfos = '%s %s' % (wxVER, pyVER)
        self.CreateStatusBar().SetStatusText(versionInfos)
        panel = MyPanel(self)
        self.Bind(wx.EVT_CLOSE, self.OnDestroy)

    def OnDestroy(self, event):
        """"""
        self.Destroy()

class MyApp(wx.App):
    """"""
    def OnInit(self):
        """"""
        self.SetClassName('MyApp')
        self.SetAppName('MyApp')
        gMainWin = MyFrame(None)
        gMainWin.SetTitle('MyFrame')
        self.SetTopWindow(gMainWin)
        gMainWin.Center()
        gMainWin.Show()
        return True

if __name__ == '__main__':
    gApp = MyApp(redirect=False,
                 filename=None,
                 useBestVisual=False,
                 clearSigInt=True)
    gApp.MainLoop()


```

</details>

**Comment by carandraug** [comment] 2020-07-07 10:09
> Here is a Py2/3 sample that works for testing with a proper panel.

I'm not sure what we're trying to test here that was not tested on the original report or what you mean with a proper panel. But I ran your code anyway and the issue is still there:

![mcow-request](https://user-images.githubusercontent.com/916140/86766239-2b985700-c042-11ea-8a25-116220806e79.png)

**Comment by Metallicow** [comment] 2020-07-07 19:45
I tested my sample on Windows to see if it was something with the frame/default color. A panel usually colors itself whatever color the OS theme is set to make it look like others. Does this occur with wxPy 4.0.x also on debian?

**Comment by carandraug** [comment] 2020-07-07 20:14
> I tested my sample on Windows to see if it was something with the frame/default color. A panel usually colors itself whatever color the OS theme is set to make it look like others. Does this occur with wxPy 4.0.x also on debian?

As I mentioned on my previous messages, the issue is that under GTK3 `GetBackgroundColour` does not work properly, it reports the wrong colour. This issue has been confirmed by wxWidgets and it will be fixed on the next wxWidgets version.

However, I think that relying on `GetBackgroundColour`, even with the upstream issue fixed, is problematic because the background might actually be a gradient or an image. Instead of having `SButton` mimic the background it should use transparency.

**Comment by Metallicow** [comment] 2020-07-07 21:02
Ok. I'd guess Robin will tag this issue as wxWidgets/GTK3 since it has been confirmed.
As far as getting it to be transparent by default, I'd think wxWidgets would have to change a bit more because of the way widgets are drawn. With my ShapedBitmapButton it kinda assumes you should know if the parent is a gradient/image/etc. The GCDC/GC classes should help with this but not all platforms handle transparency well so those changes would have to be implemented and then tested to see if It would work as one might expect.
most folks would think wx.TRANSPARENT_WINDOW would handle something like this, but it is windows only according to the docs.

**Comment by Metallicow** [comment] 2020-07-07 21:40
@carandraug I think this is what you may be desiring... Not sure if it will work right on all platforms but here is a basic sample I tested on Windows. You might be able to toy with it and get it to work somehow, but a cross compatible solution would be needed for a pull request

![transWin](https://user-images.githubusercontent.com/4668356/86846361-644f2500-c070-11ea-891f-f7941c80604b.png)


<details>
    <summary>Draw on Gradient Test - Click to expand</summary>

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

""""""

# Imports.--------------------------------------------------------------------
# -Python Imports.
import os
import sys

# -wxPython Imports.
import wx

class MyPanel(wx.Panel):
    """"""
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.BORDER_SUNKEN, name='panel'):
        """"""
        wx.Panel.__init__(self, parent, id, pos, size, style, name)

        self.SetBackgroundColour('#595188')

        p = TransPanel(self, -1, pos=(10, 10), size=(50, 50))

        self.Bind(wx.EVT_PAINT, self.OnPaint)
        # self.Bind(wx.EVT_SIZE, self.OnSize)

    def OnPaint(self, event):
        dc = wx.BufferedPaintDC(self)
        dc.GradientFillLinear(self.GetClientRect(), wx.WHITE, wx.BLACK)

    def OnSize(self, event):
        self.Refresh()

class TransPanel(wx.Panel):
    """"""
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.TRANSPARENT_WINDOW, name='panel'):
        """"""
        wx.Panel.__init__(self, parent, id, pos, size, style, name)

        # self.Bind(wx.EVT_PAINT, self.OnPaint)

        wx.CallAfter(self.Paint)
        self.Bind(wx.EVT_UPDATE_UI, self.Paint)
        self.Bind(wx.EVT_SIZE, self.OnSize)

    def Paint(self, event=None):
        dc = wx.WindowDC(self)
        gcdc = wx.GCDC(dc)
        gcdc.SetBrush(wx.TRANSPARENT_BRUSH)
        gcdc.SetPen(wx.RED_PEN)
        gcdc.DrawCircle(x=25, y=25, radius=20)

    def OnPaint(self, event):
        dc = wx.BufferedPaintDC(self)

    def OnSize(self, event):
        self.GetParent().Refresh()
        self.Refresh()
        event.Skip()


class MyFrame(wx.Frame):
    """"""
    def __init__(self, parent, id=wx.ID_ANY, title=wx.EmptyString,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.DEFAULT_FRAME_STYLE, name='frame'):
        """"""
        wx.Frame.__init__(self, parent, id, title, pos, size, style, name)
        global gMainWin
        gMainWin = self
        wxVER = 'wxPython %s' % wx.version()
        pyVER = 'python %d.%d.%d.%s' % sys.version_info[0:4]
        versionInfos = '%s %s' % (wxVER, pyVER)
        self.CreateStatusBar().SetStatusText(versionInfos)
        panel = MyPanel(self)
        self.Bind(wx.EVT_CLOSE, self.OnDestroy)

    def OnDestroy(self, event):
        """"""
        self.Destroy()

class MyApp(wx.App):
    """"""
    def OnInit(self):
        """"""
        self.SetClassName('MyApp')
        self.SetAppName('MyApp')
        gMainWin = MyFrame(None)
        gMainWin.SetTitle('MyFrame')
        self.SetTopWindow(gMainWin)
        gMainWin.Center()
        gMainWin.Show()
        return True

if __name__ == '__main__':
    gApp = MyApp(redirect=False,
                 filename=None,
                 useBestVisual=False,
                 clearSigInt=True)
    gApp.MainLoop()


```
</details>

**Comment by RobinD42** [comment] 2020-07-08 17:10
The wxWidgets fix will have been included in the latest wxPython snapshot.  Closing.

**Closed by RobinD42** 2020-07-08 17:10 UTC
