### ISSUE TITLE
fails to create mask on MacOSX with "Non-monochrome bitmap supplied"

### ISSUE THREAD

**Issue by carandraug** [wxWidgets/Phoenix#1654] opened 2020-05-31 03:25 UTC
**Operating system**: MacOSX
**wxPython version & source**: installed from PyPI "'4.1.0 osx-cocoa (phoenix) wxWidgets 3.1.4'"
**Python version & source**: python 3.6 (from the system) and 3.7 (from homebrew)

The following minimal example (it draws a circle on a bitmap to be used as a mask):

```python
import wx

app = wx.App()
size = 75
bmp = wx.Bitmap(size, size, depth=1)
dc = wx.MemoryDC()
dc.SelectObject(bmp)
dc.DrawCircle(size/2, size/2, size/3)
dc.SelectObject(wx.NullBitmap)
mask = wx.Mask(bmp)

frame = wx.Frame(None)
frame.Show()
app.MainLoop()
```

fails on Mac with the following exception:

```
Traceback (most recent call last):
[...]
    mask = wx.Mask(bmp)
wx._core.wxAssertionError: C++ assertion "v == 0 || v == 3*0xFF" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/osx/core/bitmap.cpp(1563) in InitFromMonoBitmap(): Non-monochrome bitmap supplied
```

**Comment by ARCFaria** [comment] 2020-06-05 17:08
I had the same problem.
But it was not present with wxPython 4.0.7

**Comment by RobinD42** [comment] 2020-06-17 17:39
It looks like the bitmap is being created with a depth of 32, despite the `depth=1` parameter, so the `DrawCircle` is going to do anti-aliasing to smooth the edges.

I don't think this anything specific to the wxPython part of the code. Please create a ticket for this at https://trac.wxwidgets.org/, if one doesn't already exist, and add a link to the ticket here so we can track it.

**Comment by carandraug** [comment] 2020-06-17 19:14
Done https://trac.wxwidgets.org/ticket/18792

**Comment by carandraug** [comment] 2020-06-19 19:37
wxWidgets says that this basically `depth` is ignored under OSX. To avoid the issue, we need to disable antialiasing on the graphics context. To get the graphics context we should use `wxDC.GetGraphicsContext` but that fails under wxPython because while that method does exist, it is not declared on the header files.

**Comment by swt2c** [comment] 2020-06-19 19:38
The header files come from wxWidgets though :-)

**Comment by infinity77** [comment] 2020-06-19 19:46
And there’s actually no reason for GetGraphicsContext not to be exposed in the header files of wxDC. If you can access it in C++ then you should be able to from Python. Maybe a gentle push in wxTrac may  convince The wxWidgets guys to make the modification? :-)

**Comment by RobinD42** [comment] 2020-06-19 22:12
I can add it, and `SetGraphicsContext` too. 

Keep in mind that they will only do something on OSX, and `GetGraphicsContext` will return NULL (`None`) on other platforms. (Except when you're using a `wx.GCDC`.) So you'll need to make your code conditional on the platform.

**Comment by RobinD42** [comment] 2020-06-19 22:35
It looks like at least some of the DC types in GTK3 builds set the GraphicsContext too.

**Comment by swt2c** [comment] 2020-06-21 21:13
> I can add it, and SetGraphicsContext too.
> Keep in mind that they will only do something on OSX, and GetGraphicsContext will return NULL (None) on other platforms. (Except when you're using a wx.GCDC.) So you'll need to make your code conditional on the platform.

Ah, this would need special handling in wxPython even if the methods were declared in the interface headers, right?  Because of the platform differences.

**Comment by RobinD42** [comment] 2020-06-26 19:34
No, since the methods exist in the base `wxDC` class, even though they don't do anything meaningful there, then wxPython will be happy. There are times when I do need to do something custom when methods don't exist everywhere, but this won't be one of them. The developers will need to check the return value of `GetGraphicsContext` to ensure there is one, and adapt accordingly.

**Comment by swt2c** [comment] 2020-06-26 20:09
> No, since the methods exist in the base wxDC class, even though they don't do anything meaningful there, then wxPython will be happy. There are times when I do need to do something custom when methods don't exist everywhere, but this won't be one of them. The developers will need to check the return value of GetGraphicsContext to ensure there is one, and adapt accordingly if not.

But the problem is that they are guarded by `#if wxUSE_GRAPHICS_CONTEXT`.  Is that defined on all platforms?

**Comment by swt2c** [comment] 2020-06-26 21:13
Eh, let's just try it I guess.  PR coming to see if it passes CI on all platforms.

**Comment by RobinD42** [comment] 2020-06-29 17:44
> But the problem is that they are guarded by #if wxUSE_GRAPHICS_CONTEXT. Is that defined on all platforms?

Not necessarily, but I assume that it will be in any builds intended to be used with wxPython. (The entire set of graphics context classes are not #if-guarded in wxPython.)

I've added the methods to the wxDC docs in https://github.com/wxWidgets/wxWidgets/commit/c43af017c930063fde972d5b7e01db51e409b899 so wxPython will pick it up automatically.

**Closed by RobinD42** 2020-06-29 17:44 UTC
Labels: wxWidgets

**Comment by swt2c** [comment] 2020-06-29 17:53
OK.  That's a better solution if it works.
