### ISSUE TITLE
wx.ScrolledWindow AssertionError: DoShowScrollbars(): window must be created

### ISSUE THREAD

**Issue by eldarkg** [wxWidgets/Phoenix#70] opened 2016-04-24 12:45 UTC
In python 3.5 (OS: Ubuntu 16.04):
```Python
self.general_tab_scrolledwindow = wx.ScrolledWindow( self.settings_tabs, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.HSCROLL|wx.VSCROLL )
wx._core.wxAssertionError: C++ assertion "scrolled" failed at /tmp/pip-build-jo6wg6ff/wxPython-Phoenix/ext/wxWidgets/src/gtk/scrolwin.cpp(227) in DoShowScrollbars(): window must be created
```
Part of code (generated with wxFormBuilder):
```Python
wx.Dialog.__init__ ( self, parent, id = wx.ID_ANY, title = u"Редактор настроек", pos = wx.DefaultPosition, size = wx.Size( 600,400 ), style = wx.DEFAULT_DIALOG_STYLE )

self.SetSizeHints( wx.Size( 600,400 ), wx.Size( -1,-1 ) )

sizer_settings_dialog = wx.BoxSizer( wx.VERTICAL )

self.settings_tabs = wx.Notebook( self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.NB_TOP )
self.general_tab_scrolledwindow = wx.ScrolledWindow( self.settings_tabs, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.HSCROLL|wx.VSCROLL )
```

**Comment by eldarkg** [comment] 2016-04-24 12:47
Works fine in python 3.4 (OS: Ubuntu 14.04)

**Comment by swt2c** [comment] 2016-04-25 03:39
I think this is probably a duplicate of #51.

**Comment by eldarkg** [comment] 2016-04-25 19:50
@swt2c Time will tell :) I wait merge of PR #45

**Closed** 2016-05-07 09:08 UTC
