### ISSUE TITLE
PropertyGrid.GetPropertyValue() regression in wxPython 4.1.0

### ISSUE THREAD

**Issue by dhowland** [wxWidgets/Phoenix#1663] opened 2020-06-06 01:09 UTC
**Operating system**: demonstrated on Windows and OSX
**wxPython version & source**:  pip install wxPython=4.1.0
**Python version & source**:  Python 3.8.3

**Description of the problem**:

The latest 4.1.0 release of wxPython has started throwing a `TypeError` when attempting to get the property value of an Enum property in a `PropertyGrid`.  For example:

```python
self.pg = wx.propgrid.PropertyGrid(self)
...
self.pg.Append(wx.propgrid.EnumProperty("Mode", "mode", labels=labels, values=values))
...
self.pg.SetPropertyValues({'mode': 0})
...
self.pg.GetPropertyValue('mode')
```

```
TypeError: Unexpected type ("longlong") in wxVariant.
```

This is documented in an issue on my project, here: https://github.com/dhowland/EasyAVR/issues/100

This appears to be related to an existing issue, #1299

I have not gone deep into the cause, however it appears that wxPython does not take into account that *Variant* can be `long long`.  The [documentation](https://docs.wxwidgets.org/3.0/classwx_variant.html) does make note of the possibility.

I hope that this can simply be fixed by adding the code necessary to coerce a `long long` out of wxVariant, by adding the following to `i_wxVariant_out_helper()` in [wxpy_api.sip](https://github.com/wxWidgets/Phoenix/blob/master/src/wxpy_api.sip#L364)

```
    else if (value.IsType("long long"))
        obj = PyLong_FromLongLong(value.GetLongLong());
```

**Comment by swt2c** [comment] 2020-06-07 20:01
I submitted a PR to add longlong and ulonglong to the out helper.  Hopefully that solves the problem.  This is not a problem on Linux it seems because long is 64-bit, so I am not able to test.

**Comment by dhowland** [comment] 2020-06-07 22:41
Thanks, I will test the next release and report back.

**Comment by swt2c** [comment] 2020-06-08 13:20
BTW, you state that this is a regression.  Do you know what version of wxPython in which it worked previously?

**Comment by dhowland** [comment] 2020-06-08 14:11
Well, I haven't been tracking wxPython releases, so I don't know exactly when working code turned into broken code, but it was sometime between 4.0.1 and 4.1.0.  Sorry, that's as close as I can get :(

**Comment by swt2c** [comment] 2020-06-08 14:16
> Well, I haven't been tracking wxPython releases, so I don't know exactly when working code turned into broken code, but it was sometime between 4.0.1 and 4.1.0. Sorry, that's as close as I can get :(

No problem.  I was just more curious than anything.  As best as I can tell, `wxEnumProperty` uses `long` and not `long long` on the C++ side for storing values, so it is puzzling that it is getting up converted to `long long` somewhere.

**Comment by dhowland** [comment] 2020-06-08 14:20
Yeah that's what I mean when I said I didn't go deep into the cause.  In addition to updating to 4.1.0, I also updated to Python 3.8, so I don't know the ultimate source of the long long.  However the person who reported the issue to me is on a Mac and I use Windows, so it doesn't seem to be specific to my setup.

**Comment by swt2c** [comment] 2020-06-09 22:59
So, I lied about not being able to reproduce this on Linux.  I can indeed reproduce this and #1299 on Linux.  I just failed to read the steps on #1299 .

However, I'm now thinking that the fix is incomplete as I'm still having some trouble with the PropertyGrid demo and EnumProperty.

**Comment by dhowland** [comment] 2020-06-09 23:48
Ok.  I will help if I can.  I'm not sure what trouble you're having but I can only add that this is how I worked around it for 4.1.0:

```python
        try:
            val = self.pg.GetPropertyValue('mode')
        except TypeError:
            val = self.pg.GetPropertyValueAsLongLong('mode')
```

**Comment by swt2c** [comment] 2020-06-09 23:59
So, the problem is that SetPropertyValue() doesn't work...it fails because it is apparently not a long.  Need to get to the root of why things are being converted to long longs in the first place...

**Comment by dhowland** [comment] 2020-06-10 01:36
I don't use SetPropertyValue() in my code, I use SetPropertyValues(), but it works fine with no errors.  I tried out SetPropertyValue() and sure enough it also explodes:

```
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ..\..\src\propgrid\props.cpp(1290) in wxEnumProperty::OnSetValue(): Unexpected value type
```

If I simpily remove my call to SetPropertyValues() so that nothing ever gets set to the property, it doesn't crash anymore upon GetPropertyValue().

Of course this is Python 3.8, which no longer has the distinction between 32 and 64 bit integers like Python 2.7 had.  In this case I'm using 32-bit Python 3.8 (the default install) on a 64-bit platform.  So that's probably why it's `long long` and not simply `long`.

So whatever the source of the `long long` type, it seems wx should support it.  I don't know why it wouldn't.  I don't consider it a bug to use 64-bit ints of that type.

**Closed** 2020-06-16 23:55 UTC
