### ISSUE TITLE
ModuleNotFoundError: No module named 'wx._core'

### ISSUE THREAD

**Issue by Wise-Wolf** [wxWidgets/Phoenix#2318] opened 2022-12-09 09:10 UTC
**Operating system**: Windows 10 Home, v10.0.019045 Build 19045
**wxPython version & source**:          4.2.0, installed with pip 22.3.1
**Python version & source**:            3.11.1, downloaded from python.org

**Description of the problem**:

<details>
  <summary>Trying to import wx causes a ModuleNotFoundError of a module (wx._core) that seemingly appears in the directory of the package.</summary>

```python
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lynns\AppData\Local\Programs\Python\Python311\Lib\site-packages\wx\__init__.py", line 17, in <module>
    from wx.core import *
  File "C:\Users\lynns\AppData\Local\Programs\Python\Python311\Lib\site-packages\wx\core.py", line 12, in <module>
    from ._core import *
ModuleNotFoundError: No module named 'wx._core'
```
</details>

![Directory of the package.](https://user-images.githubusercontent.com/36638584/206666363-82b8d39f-42c4-4ca4-80a3-72122ced1c07.png)

I've tried looking this problem up online (google and stackoverflow), and nothing relevant that would help me solve this issue comes up.
There doesn't seem to be anything relevant in the github issues.
I've tried reinstalling the package, both through pip, as well as from the source file (that one doesn't even succeed building, exits with code 2).
I've just gotten done uninstalling, and reinstalling everything python related on my pc. The problem still persists even after that.

What could be the cause of this?

**Comment by oleksis** [comment] 2022-12-09 10:06
Read this [comment](https://github.com/wxWidgets/Phoenix/issues/2297#issuecomment-1304778071) for Windows Artifacts

**Comment by swt2c** [comment] 2022-12-09 14:41
Duplicate of #2297.

**Closed by swt2c** 2022-12-09 14:41 UTC
