### ISSUE TITLE
--use-syswx break build in 4.1.1

### ISSUE THREAD

**Issue by kikislater** [wxWidgets/Phoenix#1911] opened 2021-01-29 03:58 UTC
**Operating system**: Archlinux / Manjaro
**wxPython version & source**:         ``` $ wx-config --version-full
3.0.5.0```
**Python version & source**:        python-3.9    

**Description of the problem**:
Using PKGBUILD, update from 4.0.7.post2 to 4.1.1 break `--use-syswx` build. Without option it build fine ! 
Command used : 
`python build.py build --release --use_syswx`

```
==> Starting build()...
Will build using: "/usr/bin/python"
3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0]
Python's architecture is 64bit
cfg.VERSION: 4.1.1

Running command: build
Running command: build_wx
use_syswx option specified, skipping wxWidgets build
Finished command: build_wx (0.0s)
Running command: build_py
Checking for /home/sylvain/build/python-wxpython/repos/community-x86_64/src/wxPython-4.1.1/bin/waf-2.0.19...
"/usr/bin/python" /home/sylvain/build/python-wxpython/repos/community-x86_64/src/wxPython-4.1.1/bin/waf-2.0.19 --wx_config=wx-config-gtk3 --gtk3 --python="/usr/bin/python" --out=build/waf/3.9/gtk3 configure build 
Setting top to                           : /home/sylvain/build/python-wxpython/repos/community-x86_64/src/wxPython-4.1.1 
Setting out to                           : /home/sylvain/build/python-wxpython/repos/community-x86_64/src/wxPython-4.1.1/build/waf/3.9/gtk3 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'python'            : /usr/bin/python 
Checking for python version >= 2.7.0     : 3.9.1 
python-config                            : /usr/bin/python-config 
Asking python-config for pyext '--cflags --libs --ldflags' flags : yes 
Testing pyext configuration                                      : yes 
Finding libs for WX                                              : yes 
Finding libs for WXADV                                           : yes 
Finding libs for WXSTC                                           : yes 
Finding libs for WXHTML                                          : yes 
Finding libs for WXGL                                            : yes 
Finding libs for WXWEBVIEW                                       : yes 
Finding libs for WXXML                                           : yes 
Finding libs for WXXRC                                           : yes 
Finding libs for WXRICHTEXT                                      : yes 
Finding libs for WXMEDIA                                         : yes 
Finding libs for WXRIBBON                                        : yes 
Finding libs for WXPROPGRID                                      : yes 
Finding libs for WXAUI                                           : yes 
'configure' finished successfully (0.828s)
Waf: Entering directory `/home/sylvain/build/python-wxpython/repos/community-x86_64/src/wxPython-4.1.1/build/waf/3.9/gtk3'
**** Compiler: /usr/bin/gcc --version
     gcc (GCC) 10.2.0
     Copyright (C) 2020 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[  1/921] Compiling sip/siplib/qtlib.c
[  2/921] Compiling sip/siplib/bool.cpp
[  3/921] Compiling sip/siplib/apiversions.c
[  4/921] Compiling sip/siplib/objmap.c
[  5/921] Compiling sip/siplib/voidptr.c
[  6/921] Compiling sip/siplib/int_convertors.c
[  7/921] Compiling sip/siplib/array.c
[  8/921] Compiling sip/siplib/threads.c
[  9/921] Compiling sip/siplib/descriptors.c
[ 10/921] Compiling sip/siplib/siplib.c
[ 11/921] Compiling sip/cpp/sip_corewxLogTextCtrl.cpp
[ 12/921] Compiling sip/cpp/sip_corewxEvtHandler.cpp
[ 13/921] Compiling sip/cpp/sip_corewxCollapsiblePaneEvent.cpp
[ 14/921] Compiling sip/cpp/sip_corewxAutoBufferedPaintDC.cpp
[ 15/921] Compiling sip/cpp/sip_corewxAccessible.cpp
[ 16/921] Compiling sip/cpp/sip_corewxLogStderr.cpp
[ 17/921] Compiling sip/cpp/sip_corewxLogRecordInfo.cpp
In file included from ../../../../sip/cpp/sip_corewxLogTextCtrl.cpp:10:
../../../../sip/cpp/sipAPI_core.h:21220:10: fatal error: wx/collheaderctrl.h: No such file or directory
21220 | #include <wx/collheaderctrl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../../../../sip/cpp/sip_corewxEvtHandler.cpp:10:
../../../../sip/cpp/sipAPI_core.h:21220:10: fatal error: wx/collheaderctrl.h: No such file or directory
21220 | #include <wx/collheaderctrl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../../../../sip/cpp/sip_corewxCollapsiblePaneEvent.cpp:10:
../../../../sip/cpp/sipAPI_core.h:21220:10: fatal error: wx/collheaderctrl.h: No such file or directory
21220 | #include <wx/collheaderctrl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../../../../sip/cpp/sip_corewxAutoBufferedPaintDC.cpp:10:
../../../../sip/cpp/sipAPI_core.h:21220:10: fatal error: wx/collheaderctrl.h: No such file or directory
21220 | #include <wx/collheaderctrl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../../../../sip/cpp/sip_corewxAccessible.cpp:10:
../../../../sip/cpp/sipAPI_core.h:21220:10: fatal error: wx/collheaderctrl.h: No such file or directory
21220 | #include <wx/collheaderctrl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../../../../sip/cpp/sip_corewxLogStderr.cpp:10:
../../../../sip/cpp/sipAPI_core.h:21220:10: fatal error: wx/collheaderctrl.h: No such file or directory
21220 | #include <wx/collheaderctrl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In file included from ../../../../sip/cpp/sip_corewxLogRecordInfo.cpp:10:
../../../../sip/cpp/sipAPI_core.h:21220:10: fatal error: wx/collheaderctrl.h: No such file or directory
21220 | #include <wx/collheaderctrl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Waf: Leaving directory `/home/sylvain/build/python-wxpython/repos/community-x86_64/src/wxPython-4.1.1/build/waf/3.9/gtk3'
Build failed
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
Command '"/usr/bin/python" /home/sylvain/build/python-wxpython/repos/community-x86_64/src/wxPython-4.1.1/bin/waf-2.0.19 --wx_config=wx-config-gtk3 --gtk3 --python="/usr/bin/python" --out=build/waf/3.9/gtk3 configure build ' failed with exit code 1.
Finished command: build_py (0m4.749s)
Finished command: build (0m4.749s)
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by swt2c** [comment] 2021-01-29 04:11
Somewhat of a duplicate of #1909.

4.1.x won't realistically support building with wxWidgets 3.0.x.  4.1.x is based on wxWidgets 3.1.x.

**Comment by kikislater** [comment] 2021-01-29 13:09
You are right ! Same error as #1909 when I build wxPython 4.1.1 against wxWidgets 3.1.4 ... 
Any bindings to disable EnableVisibleFocus ?

**Comment by swt2c** [comment] 2021-08-25 00:24
Duplicate of #1909.

**Closed by swt2c** 2021-08-25 00:24 UTC

**Comment by shivanandagouda73** [comment] 2022-12-15 06:19
same error how to solved the error plz can you help me

**Comment by shivanandagouda73** [comment] 2022-12-15 06:21
same error how to solved error can you plz help me
