### ISSUE TITLE
4-byte characters (emojis) in StaticText/TextCtrl/Button/ListCtrl/... labels or values cause string truncation

### ISSUE THREAD

**Issue by Remboooo** [wxWidgets/Phoenix#2537] opened 2024-02-29 10:15 UTC
**Operating system**: Windows 11 23H2
**wxPython version & source**:
pypi 4.2.1
```
>>> import wx
>>> print(wx.PlatformInfo)
('__WXMSW__', 'wxMSW', 'unicode', 'unicode-wchar', 'wx-assertions-on', 'phoenix', 'wxWidgets 3.2.2.1', 'autoidman', 'sip-6.7.9', 'build-type: release')
```
**Python version & source**:
stock
```
python -VV
Python 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
```

**Description of the problem**:
When value/label strings on controls contain emojis (4 byte characters), the string is truncated 1 byte too early for every such character in the string.
This means that for every such character (e.g. emoji) in the string, a dummy character needs to be added to the end for the string not to be truncated.

Example: having labels with the following strings:
"Test 🐛"
"Test 🐛_"
"Test 🐛🐛_"
"Test 🐛🐛__"
"🐛🐛🐛 This should count to 5: 12345"

results in the following:
<img width="206" alt="image" src="https://github.com/wxWidgets/Phoenix/assets/1052610/9a40ae5d-e062-42c7-91d8-de58a0aff989">

This happens at least for `StaticText`, `TextCtrl`, `Button` and `ListCtrl`. I haven't tried any others.

<details>
  <summary>Code Example (click to expand)</summary>

```python
import wx


class TestFrame(wx.Frame):
	def __init__(self, parent):
		wx.Frame.__init__(
			self, parent, id=wx.ID_ANY, title="Test", pos=wx.DefaultPosition, size=wx.Size(500, 300), style=wx.DEFAULT_FRAME_STYLE | wx.TAB_TRAVERSAL
		)

		sizer = wx.BoxSizer(wx.VERTICAL)

		text1 = wx.StaticText(self, wx.ID_ANY, u"Test 🐛", wx.DefaultPosition, wx.DefaultSize, 0)
		sizer.Add(text1, 0, wx.ALL | wx.EXPAND, 5)

		text2 = wx.StaticText(self, wx.ID_ANY, u"Test 🐛_", wx.DefaultPosition, wx.DefaultSize, 0)
		sizer.Add(text2, 0, wx.ALL | wx.EXPAND, 5)

		text3 = wx.StaticText(self, wx.ID_ANY, u"Test 🐛🐛_", wx.DefaultPosition, wx.DefaultSize, 0)
		sizer.Add(text3, 0, wx.ALL | wx.EXPAND, 5)

		text4 = wx.StaticText(self, wx.ID_ANY, u"Test 🐛🐛__", wx.DefaultPosition, wx.DefaultSize, 0)
		sizer.Add(text4, 0, wx.ALL | wx.EXPAND, 5)

		text5 = wx.StaticText(self, wx.ID_ANY, u"🐛🐛🐛 This should count to 5: 12345", wx.DefaultPosition, wx.DefaultSize, 0)
		sizer.Add(text5, 0, wx.ALL | wx.EXPAND, 5)

		self.SetSizer(sizer)
		self.Layout()


if __name__ == '__main__':
	app = wx.App()
	frm = TestFrame(None)
	frm.Show()
	app.MainLoop()
```
</details>

**Comment by AmyAmy** [comment] 2024-02-29 11:34
This seems to work fine when using `�` (U+FFFD). Which is the last displayable character which encodes to three UTF-8 codepoints, the last displayable character to encode to one UTF-16 codepoint, and the last displayable character on the BMP:

<img src="https://github.com/wxWidgets/Phoenix/assets/630387/2fa46e56-5296-4e27-b1e0-52d36ea8cbd1)" width="300" />

It breaks when using `𐀁` (U+10001). Which is the first character which encodes to four UTF-8 codepoints, and to two UTF-16 codepoints, and the first character not on the BMP:

<img src="https://github.com/wxWidgets/Phoenix/assets/630387/db616787-0862-4fc9-973e-a3a8c5350886)" width="300" />

(The font doesn't have glyph for this character, but that shouldn't matter for this issue).

**Comment by swt2c** [comment] 2024-02-29 14:13
I believe this is a duplicate of #2446 (fixed in git).  Please test the latest snapshots.

**Closed** 2024-03-04 17:57 UTC
