### ISSUE TITLE
wrapped C/C++ object of type BoxSizer has been deleted

### ISSUE THREAD

**Issue by The-Pack-Man** [wxWidgets/Phoenix#910] opened 2018-07-03 17:53 UTC
**Operating system**: Windows 10
**wxPython version**:4.0.3
**Stock or custom build**: Stock
**Python version**: 3.6
**Stock or custom build**: Stock

**Description of the problem**: When I try to add 4 collapsible panels using the documentation https://wxpython.org/Phoenix/docs/html/wx.CollapsiblePane.html here as a reference I receive the error wrapped C/C++ object of type BoxSizer has been deleted.

```python
# Put code sample here
```
#Creates accordion panels
        collapsible_panel1=wx.CollapsiblePane(machineInfo, label="Machine Info 1", size=(wx.EXPAND,30))
        collapsible_panel2=wx.CollapsiblePane(machineInfo, label="Machine Info 2", size=(wx.EXPAND,30))
        collapsible_panel3=wx.CollapsiblePane(machineInfo, label="Machine Info 3", size=(wx.EXPAND,30))
        collapsible_panel4=wx.CollapsiblePane(machineInfo, label="Machine Info 4", size=(wx.EXPAND,30))
        
        #Gets panes to put data into them
        pane1=collapsible_panel1.GetPane()
        pane2=collapsible_panel2.GetPane()
        pane3=collapsible_panel3.GetPane()
        pane4=collapsible_panel3.GetPane()
        
        #creates sizers for all panes
        paneSz1=wx.BoxSizer(wx.VERTICAL)
        paneSz2=wx.BoxSizer(wx.VERTICAL)
        paneSz3=wx.BoxSizer(wx.VERTICAL)
        paneSz4=wx.BoxSizer(wx.VERTICAL)
        
        #self.panel.SetSizerAndFit( machineInfoSizer )
        self.Fit()
        
        #Adds accordion panels with some optional spacing
        machineInfoSizer.Add(collapsible_panel1,proportion=0)
        #machineInfoSizer.AddSpacer(3) 
        machineInfoSizer.Add(collapsible_panel2,proportion=0)
        #machineInfoSizer.AddSpacer(3) 
        machineInfoSizer.Add(collapsible_panel3,proportion=0)
        #machineInfoSizer.AddSpacer(3) 
        machineInfoSizer.Add(collapsible_panel4, proportion=0)
        #machineInfoSizer.AddSpacer(3) 
        
        #Add content to panes here
        paneSz1.Add(wx.StaticText(pane1, wx.ID_ANY, "test!"), 1, wx.GROW | wx.ALL, 2)
        paneSz2.Add(wx.StaticText(pane2, wx.ID_ANY, "test!"), 1, wx.GROW | wx.ALL, 2)
        paneSz3.Add(wx.StaticText(pane3, wx.ID_ANY, "test!"), 1, wx.GROW | wx.ALL, 2)
        paneSz4.Add(wx.StaticText(pane4, wx.ID_ANY, "test!"), 1, wx.GROW | wx.ALL, 2)
        
        #Sets sizer for all panes
        pane1.SetSizer(paneSz1)
        pane2.SetSizer(paneSz2)
        pane3.SetSizer(paneSz3)
        pane4.SetSizer(paneSz4)
        
        #Sets size hints for all panes
        paneSz1.SetSizeHints(pane1)
        paneSz2.SetSizeHints(pane2)
        paneSz3.SetSizeHints(pane3)
        paneSz4.SetSizeHints(pane4)

self.SetSizerAndFit(machineInfoSizer, deleteOld=True)

Here is my stack for this error:
Traceback (most recent call last):
  File "C:\Users\packawd\My Documents\LiClipse Workspace\GUI\GUI.py", line 172, in <module>
    main()
  File "C:\Users\packawd\My Documents\LiClipse Workspace\GUI\GUI.py", line 166, in main
    ex = Example(None)
  File "C:\Users\packawd\My Documents\LiClipse Workspace\GUI\GUI.py", line 14, in __init__
    self.InitUI()
  File "C:\Users\packawd\My Documents\LiClipse Workspace\GUI\GUI.py", line 134, in InitUI
    paneSz3.SetSizeHints(pane3)
RuntimeError: wrapped C/C++ object of type BoxSizer has been deleted

Everything else relates to the menu or other elements that should be default. If possible I would like to know how to add multiple accordions correctly for my application.

**Comment by mesalu** [comment] 2018-07-03 18:31
Your bug is here:
``` Python    
    pane3=collapsible_panel3.GetPane()
    pane4=collapsible_panel3.GetPane()
```

`pane3` and `pane4` are the same panel, from `collapsible_panel3`. 

When you assign the sizer for `pane4`,  the previously assigned sizer gets deleted by default:

"""
deleteOld (bool) – If True (the default), this will delete any pre-existing sizer. Pass False if you wish to handle deleting the old sizer yourself but remember to do it yourself in this case to avoid memory leaks.
"""

I strongly recommend condensing this into a loop. :) 
It'll help you keep things straight. 

Something like this:

```Python
for x in range(4):
            print("Iterating panel: {}".format(x+1))
            collapsible_panel = wx.CollapsiblePane(self, label="Machine Info {}".format(x+1))
            machineInfoSizer.Add(collapsible_panel, 0)

            panel = collapsible_panel.GetPane()
            psizer = wx.BoxSizer(wx.VERTICAL)
            psizer.Add(wx.StaticText(panel, wx.NewId(), "Test {}!".format(x+1)), 1, wx.EXPAND | wx.ALL, 2)

            panel.SetSizer(psizer)

            psizer.SetSizeHints(panel)
```

**Comment by mesalu** [comment] 2018-07-03 18:37
Another comment I had:
I'm not really sure what `wx.EXPAND` is doing in your size tuple. `wx.EXPAND` is a bit-flag that is equivalent to `wx.GROW`, and really only has meaning when provided to a `Sizer` object or some widget that's expecting to pass flags around. Using it for size would create (at least on my system) a widget that's 8192 pixels wide. 

Closing issue, not a bug with wxPython or wxWidgets.

**Closed by mesalu** 2018-07-03 18:37 UTC

**Comment by The-Pack-Man** [comment] 2018-07-03 18:45
Thank you Mr. Mesalu for the help and suggestions.

I am fairly new to wxPython, and did not really know how/where to ask for help. So that is also why I was not so good with the wx.Expand vs. wx.Grow. Though when I try your loop it changes the position of the my panel and seems to deactivate some buttons. Not sure what that is about.

**Comment by mesalu** [comment] 2018-07-03 18:47
Questions for new users are best placed in the wxpython-users mailing list. 
https://groups.google.com/forum/#!forum/wxpython-users
