### ISSUE TITLE
StyledTextCtrl. SetText and emoji

### ISSUE THREAD

**Issue by Jenyay** [wxWidgets/Phoenix#2472] opened 2023-11-03 10:03 UTC
**Operating system**: Windows 10 (everything is fine on Linux)
**wxPython version & source**: 4.2.1
**Python version & source**:  Python 3.8

**Description of the problem**: If there are some emoji (📌, 💡, 💾) in the text, inserting the text using SetText() will trim the last character.

```python
import wx
import wx.stc

class TestFrame(wx.Frame):
    def __init__(self, parent, title):
        wx.Frame.__init__(self, parent, wx.ID_ANY, title, size=(400, 300))
        self.text = wx.stc.StyledTextCtrl(self)
        self.text.SetText("📌 111 222 333")

if __name__ == '__main__':
    app = wx.App()
    frame = TestFrame(None, 'StyledTextCtrl Test')
    frame.Show()
    app.MainLoop()

```

Result:
![StyledTextCtrl Test](https://github.com/wxWidgets/Phoenix/assets/166281/a7924cc3-ad65-4e67-8d90-6667d38ca913)

**Comment by reticulatus** [comment] 2023-11-03 11:05
It's probably related to the following issue: https://github.com/wxWidgets/Phoenix/issues/2446

**Comment by swt2c** [comment] 2023-11-03 14:13
Yes, I think it's a duplicate of #2446.

**Closed** 2023-11-28 00:52 UTC

**Comment by Metallicow** [comment] 2024-01-30 00:55
Umm yeah I think you nailed the issue.

... but always remember all Llama emoji are at LEAST 2 chars long haha...
