### ISSUE TITLE
FloatSpin widget and GTK3: two values displayed?

### ISSUE THREAD

**Issue by kierun** [wxWidgets/Phoenix#564] opened 2017-10-05 14:53 UTC
**Operating system**:

CentOS 7.

Linux serval 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 

**wxPython version**:

4.0.0b2

**Stock or custom build**:

Stock, installed with `pip`.

**Python version**:

3.6.2

**Stock or custom build**:

Stock, installed via `yum`.

**Description of the problem**:

The `wx.lib.agw.floatspin.FlaotSpin` looks weird on Linux (GTK3) but works fine on Windows.

![untitled](https://user-images.githubusercontent.com/3079575/31233644-05a1ab76-a9e5-11e7-8873-db96f91dadda.png)

```python
import wx.lib.agw.floatspin as FS

 _spin_ctrl_current = FS.FloatSpin(
       panel,
       wx.ID_ANY,
       size=(-1, -1),
       value=0.0,
       min_val=0.0,
       max_val=20.0,
       increment=0.1)
```

**Comment by kierun** [comment] 2017-10-09 08:25
Can anyone confirm that this is happen to them as well or is it just me?… Thanks.

**Comment by HelioGuilherme66** [comment] 2017-10-09 09:39
@kierun Yes, you are not the only one to see it :)
I confirm the bug on Fedora Core 26, with 4.0.0rc1 from Git built on GTK3.

**Comment by HelioGuilherme66** [comment] 2017-10-28 21:57
Here is a comparison on GTK2 vs GTK3:
![imagem](https://user-images.githubusercontent.com/2866630/32138901-5aa0c5c0-bc33-11e7-9d7c-1aaefe46e418.png)

**Comment by swt2c** [comment] 2017-11-01 00:22
I think this is the root cause:
https://trac.wxwidgets.org/ticket/17847

As a workaround, you can use `wx.SpinCtrlDouble` which is probably a better solution anyway as it's a native wxWidget.

**Comment by swt2c** [comment] 2017-12-01 03:24
I believe this should be fixed now in the latest snapshots.

**Comment by mesalu** [comment] 2018-01-05 23:54
Addressed by: https://trac.wxwidgets.org/ticket/17847
Fixed by @swt2c in wxWidgets/wxWidgets/issues/611 
Tweaked and committed by Paul in 9ae5bf06b9ff3c0373c5c3b284c129d503d1d435,
Which is included with where ext/wxWidgets is currently set.

Thanks guys!

**Closed** 2018-01-05 23:56 UTC
Labels: wxWidgets
