### ISSUE TITLE
pip install from git / compiling fails under Windows

### ISSUE THREAD

**Issue by jesse-git** [wxWidgets/Phoenix#57] opened 2016-03-28 00:43 UTC
Windows 7 x64
Python 3.5 x64
MSVC 2015 Update 1 (14.0)

(I am not that familiar with the internals of wxpython.)
I tried requiring wxpython in setup.py and building from the git source (not using wheels from http://wxpython.org/Phoenix/snapshot-builds/) using the recommended compiler for python 3.5. Several things do compile correctly, but then it:
- Prints a "warning": `WARNING: msgfmt command not found, message catalogs not rebulit. Please install`gettext`and associated tools.` then continues on its merry way. (Does this warning matter? Where would I find `gettext`?)
- Stops at: `FileNotFoundError: [Errno 2] No such file or directory: 'sip\\cpp\\_core.sbf'` (why is this missing?)

Log:

```
<snip>
    glcmn.cpp
        cl /c /nologo /TP /Fovc140_mswudll_x64\gldll_glcanvas.obj /MD /DWIN32  /Zi  /Fd..\..\lib\vc140_x64_dll\wxmsw30u_gl_vc140_x64.pdb   /O2 /D_CRT_SECURE_NO_DEPRECATE=1
 /D_CRT_NON_CONFORMING_SWPRINTFS=1 /D_SCL_SECURE_NO_WARNINGS=1  /D__NO_VC_CRTDBG__ /D__WXMSW__    /DNDEBUG     /D_UNICODE   /I..\..\lib\vc140_x64_dll\mswu /I..\..\include
/W4  /DWXBUILDING /I..\..\src\tiff\libtiff /I..\..\src\jpeg /I..\..\src\png  /I..\..\src\zlib /I..\..\src\regex /I..\..\src\expat\lib /DWXUSINGDLL  /DWXMAKINGDLL_GL /GR /EHsc /Yu"wx/wxprec.h"  /Fp"vc140_mswudll_x64\wxprec_gldll.pch"   ..\..\src\msw\glcanvas.cpp
    glcanvas.cpp
        rc /fovc140_mswudll_x64\gldll_version.res  /d WIN32  /d _CRT_SECURE_NO_DEPRECATE=1 /d _CRT_NON_CONFORMING_SWPRINTFS=1 /d _SCL_SECURE_NO_WARNINGS=1 /d __NO_VC_CRTDBG__  /d __WXMSW__   /d NDEBUG    /d _UNICODE  /i ..\..\lib\vc140_x64_dll\mswu /i ..\..\include  /d WXBUILDING /d WXDLLNAME=wxmsw30u_gl_vc140_x64  /i ..\..\src\tiff\libtiff /i ..\..\src\jpeg /i ..\..\src\png /i ..\..\src\zlib /i ..\..\src\regex /i ..\..\src\expat\lib /d WXUSINGDLL /d WXMAKINGDLL_GL ..\..\src\msw\version.rc
    Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
    Copyright (C) Microsoft Corporation.  All rights reserved.

        link /DLL /NOLOGO /OUT:..\..\lib\vc140_x64_dll\wxmsw30u_gl_vc140_x64.dll  /DEBUG /pdb:"..\..\lib\vc140_x64_dll\wxmsw30u_gl_vc140_x64.pdb" /opt:ref /opt:icf  /MACHINE:X64 /LIBPATH:..\..\lib\vc140_x64_dll   @F:\temp\nmFED1.tmp
       Creating library ..\..\lib\vc140_x64_dll\wxmsw30u_gl.lib and object ..\..\lib\vc140_x64_dll\wxmsw30u_gl.exp
    WARNING: msgfmt command not found, message catalogs not rebulit.
             Please install gettext and associated tools.
    Finished command: build_wx (7m11.263s)
    Running command: build_py
    Checking for F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf-1.7.15-p1...
    Not found.  Attempting to download...
    Connection successful...
    Data downloaded...
    Checking for F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf-1.7.15-p1...
    MSVC: E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe
    "h:\mydocu~1\progra~1\worksp~1\photos~2\symbio~2\env\scripts\python.exe" F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf-1.7.15-p1 --msvc_arch=x64 --python="h:\mydocu~1\progra~1\worksp~1\photos~2\symbio~2\env\scripts\python.exe" --out=build/waf/3.5/x64/release configure build
    Setting top to                           : F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964
    Setting out to                           : F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\build\waf\3.5\x64\release
    Checking for program CL                  : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\x86_ARM\CL.exe
    Checking for program CL                  : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\amd64\CL.exe
    Checking for program CL                  : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\x86_amd64\CL.exe
    Checking for program CL                  : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\amd64\CL.exe
    Checking for program CL                  : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\CL.exe
    Checking for program CL                  : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\amd64\CL.exe
    Checking for program CL                  : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\amd64\CL.exe
    Checking for program LINK                : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\amd64\LINK.exe
    Checking for program LIB                 : E:\Program Files (x86)\Microsoft Visual
 Studio 14.0\VC\BIN\amd64\LIB.exe
    Checking for program MT                  : C:\Program Files (x86)\Windows Kits\10\bin\x64\MT.exe
    Checking for program RC                  : C:\Program Files (x86)\Windows Kits\10\bin\x64\RC.exe
    Checking for program python              : h:\mydocu~1\progra~1\worksp~1\photos~2\symbio~2\env\scripts\python.exe
    Checking for python version              : (3, 5, 1, 'final', 0)
    'configure' finished successfully (34.820s)
    Waf: Entering directory `F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\build\waf\3.5\x64\release'
    Traceback (most recent call last):
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Scripting.py", line 97, in waf_entry_point
        run_commands()
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Scripting.py", line 153, in run_commands
        ctx=run_command(cmd_name)
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Scripting.py", line 146, in run_command
        ctx.execute()
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Scripting.py", line 353, in execute
        return execute_method(self)
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Build.py", line 106, in execute
        self.execute_build()
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Build.py", line 109, in execute_build
        self.recurse([self.run_dir])
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Context.py", line 125, in recurse
        user_function(self)
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\wscript", line 466, in build
        source   = getEtgSipCppFiles(etg) + rc,
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\buildtools\config.py", line 634, in getEtgSipCppFiles
        return _getSbfValue(etg, 'sources')
      File "F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\buildtools\config.py", line 627, in _getSbfValue
        for line in open(sbf):
    FileNotFoundError: [Errno 2] No such file or directory: 'sip\\cpp\\_core.sbf'
    Command '"h:\mydocu~1\progra~1\worksp~1\photos~2\symbio~2\env\scripts\python.exe" F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\bin\waf-1.7.15-p1 --msvc_arch=x64 --python="h:\mydocu~1\progra~1\worksp~1\photos~2\symbio~2\env\scripts\python.exe" --out=build/waf/3.5/x64/release configure build ' failed with exit code 2.
    Finished command: build_py (0m49.505s)
    Finished command: build (8m0.768s)
    Command 'h:\mydocu~1\progra~1\worksp~1\photos~2\symbio~2\env\scripts\python.exe -u
 build.py build' failed with exit code 2.

    ----------------------------------------
Command "h:\mydocu~1\progra~1\worksp~1\photos~2\symbio~2\env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='F:\\temp\\pip-build-zda2eowp\\wxPython-Phoenix-3.0.3.dev1964\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record F:\temp\pip-8zmht2kw-record\install-record.txt --single-version-externally-managed --compile --install-headers h:\mydocu~1\progra~1\worksp~1\photos~2\symbio~2\env\include\site\python3.5\wxpython-phoenix" failed with error code 2 in F:\temp\pip-build-zda2eowp\wxPython-Phoenix-3.0.3.dev1964\
```

**Comment by DietmarSchwertberger** [comment] 2016-03-28 13:01
I don't think that submitting an issue here makes too much sense without checking for the reasons before...
What command line did you try for the build?
Did you follow the build instructions? For a build from git, this command line is listed in the build instructions:
python build.py dox etg --nodoc sip build

**Comment by jesse-git** [comment] 2016-03-28 21:52
Sorry, I didn't know about the mailing lists. I created an issue on github because I do believe there is an issue somewhere along the way here, either with code or documentation that could be improved, and obviously there is also an issue with wxpython.org. In my experience, if an issue is never created in an issue tracking system and the problem is only discussed through email / a mailing list, no action will be taken. So, I would very much appreciate it if someone could help out on github. Github issues provide a nice way to keep track of "todos" that is also standardized, compared to flagging emails / messages on a message board, so I am used to github and do not have accounts elsewhere for mailing lists.

In any case, I did already see the command you listed, but I'm not building wxpython directly from the command line. I'm writing a program with wxpython that should be installable cross-platform easily with pip using one simple command - the standard `pip install myapp`. I would think this would be the most common scenario for every dev who is using wxpython. As it is the standard way of doing things, all dependencies should be brought down using that command, preferably from the the official pypi server with the second choice being github, and any compiling/buliding steps required by python dependencies should be automatically triggered by it. I can't find the correct documentation to do this, and maybe I am doing something wrong. Simply adding the following to my setup.py doesn't work:

```
<snip>
setup(
	name = "myapp",
	version = "0.1.0.dev0001",
<snip>
	install_requires = ["wxPython_Phoenix		>=3.0.3.dev1964, <3.1",
						"sqlalchemy				>=1.0.12, <1.1",
						"mysql-connector-python	>=2.1.3,  <2.2",],
	dependency_links = [
		"git+https://github.com/wxWidgets/Phoenix@f780b21#egg=wxPython_Phoenix-3.0.3.dev1964",
	],
<snip>
```

Thanks

**Comment by DietmarSchwertberger** [comment] 2016-03-28 23:29
Well, if a package does not build if you throw any command at it instead of the documented one, I would not really call this an issue.

Either use the .whl or call the build.py script with the appropriate commands.
For the .whl files from the snapshot there's documentation available at http://wiki.wxpython.org/How%20to%20install%20wxPython#Installing_wxPython-Phoenix_using_pip

**Comment by jesse-git** [comment] 2016-04-07 01:14
I am not using .whl files from a 3rd party website, especially a currently compromised website which seems to not be maintained, as the problem hasn't been fixed yet. I don't think that's unreasonable. This is the very reason why the people behind pip have forced the extra step of using `--trusted-host` and `--allow-external` and encourage only the official pypi server to be used, as it is well maintained, secured, and understood. I am not sure to whom this issue should be reported to.

As far as building, perhaps the real issue is how to execute the equivalent of the build command from within setuptools in `setup.py`, and why is it not currently being executed via the setuptools install action? Specifying phoenix's dependencies/submodules one by one to build them (as in the documented build command) is doable by a human, but it also needs to be triggered by the install action of phoenix's `setup.py`. Otherwise, it breaks the installation of the whole dependency chain of anyone requiring phoenix as a dependency in their project.

To this end, I took a look at `setup.py`:
https://github.com/wxWidgets/Phoenix/blob/9b224fcb3162f385c8eaf06dadcc2e13a5735841/setup.py#L216
The `build` command is being executed as part of `install`, so that's good...

https://github.com/wxWidgets/Phoenix/blob/9b224fcb3162f385c8eaf06dadcc2e13a5735841/setup.py#L100
The build command has been slightly overridden from setuptools default, but it has no reference to the required `dox etg --nodoc sip build`. This would seem to be the logical place to put it. I haven't tried it myself yet because I started another project (without need for wxpython). However, this would be great to fix and have the ability for wxpython to be easily specified as a dependency in the standard way.

**Comment by RobinD42** [comment] 2016-05-11 06:01
It's been a while since I tested it, but all should be in place for a standard build using just pip and a source tarball.  However I did not think about pip fetching direct from github, and I expect that is where the problem is.  The pip/setuptools style approach assumes that all of the generated code is already present, but that code is not committed to the git repository.  In fact, there should be a warning printed somewhere in your log to that effect.

I'm reluctant to put generated code in a VCS, as that is generally frowned upon.  But I'm also not sure I want the whole set of build commands to be run from a pip build as that is still a little fragile currently so less failure points is better.  We're moving forward again towards getting Phoenix into PyPi, but I'm open to suggestions about what to do in the meantime.

P.S. The website has been cleaned and Google says they have removed their flags from the listings.  It was a gnarly issue that took several rounds of fixes.

**Comment by fbender** [comment] 2016-06-12 11:32
> I'm reluctant to put generated code in a VCS, as that is generally frowned upon.

You can setup a CI tool to generate/compile everything for you and then upload the builds as fragments to the [Github releases page](https://github.com/wxWidgets/Phoenix/releases) (e.g. using [travis-ci](https://docs.travis-ci.com/user/deployment/releases) and/or [appveyor](https://www.appveyor.com/docs/deployment/github)). I guess you can just have a tag per released version as well as a "latest" tag (or similar) that you update regularly.

**Closed** 2018-07-31 16:55 UTC
