### ISSUE TITLE
exception with TextCompleter

### ISSUE THREAD

**Issue by mprosperi** [wxWidgets/Phoenix#49] opened 2016-03-11 10:45 UTC
the problem is described here:
http://stackoverflow.com/questions/31243376/wxpython-writing-auto-completer
and is still present on the latest whl (March 10, 2016)
Just tried with python 3.4 on win7/64bit, wxPython_Phoenix-3.0.3.dev1964+f780b21-cp34-cp34m-win_amd64

**Comment by swt2c** [comment] 2016-03-17 04:03
You need to pass an instance of MyTextCompleter to wx.TextCtrl.AutoComplete().  Change this:
`text.AutoComplete(MyTextCompleter)` to `text.AutoComplete(MyTextCompleter())`.

I'll see if I can figure out how to submit a PR to update the example.

**Comment by swt2c** [comment] 2016-03-17 04:11
https://github.com/wxWidgets/Phoenix/pull/52

**Comment by mprosperi** [comment] 2016-03-17 08:56
thank you but with your suggested change the SO example crashes the python interpreter

**Comment by mprosperi** [comment] 2016-03-17 09:05
...when you start typing in textctrl

**Comment by HelioGuilherme66** [comment] 2016-03-17 13:11
I think we must do:
```
mytextcompleter = MyTextCompleter()
text.AutoComplete(mytextcompleter)
```

**Comment by swt2c** [comment] 2016-03-17 13:33
I can't reproduce that easily because wx.TextCtrl.AutoComplete(wx.TextCompleter) isn't implemented on wxGTK.  :-(

Does @HelioGuilherme66 suggestion work?  If so, then there is probably a memory management bug here.  The [wxWidgets documentation](http://docs.wxwidgets.org/trunk/classwx_text_entry.html#ae8ca40185ba6bbaacb4715039d73342b) says that wxTextEntry is supposed to take control of the object and delete it when it is done with it.  I suspect Python may be releasing the object before wxTextEntry is done with it.

**Comment by HelioGuilherme66** [comment] 2016-03-17 16:55
Actually, the code runs without my proposal (I have it commented in my code). Sorry.
I am too with Linux, and the autocomplete does not work.

**Comment by swt2c** [comment] 2016-03-18 02:57
@mprosperi, can you see if this PR fixes the crash:
https://github.com/wxWidgets/Phoenix/pull/53

**Comment by swt2c** [comment] 2016-05-04 04:02
@mprosperi, it looks like Robin merged my PR.  Can you try the latest snapshot build now and see if the crash is fixed?

**Comment by mprosperi** [comment] 2016-05-08 04:41
yes, it's fixed

**Comment by swt2c** [comment] 2016-08-21 19:15
Can you close this issue please?

**Closed** 2016-08-23 08:07 UTC
