### ISSUE TITLE
Problem with installation 4.2.0 from pip on Fedora 37

### ISSUE THREAD

**Issue by evgnor86** [wxWidgets/Phoenix#2334] opened 2023-01-30 04:03 UTC
Hello!

Fedora 37 / Python 3.11

pip install wxPython
Defaulting to user installation because normal site-packages is not writeable
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hqjgw1ta/wxpython_131bce18595a4c66b1d958caed495bf6/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-hqjgw1ta/wxpython_131bce18595a4c66b1d958caed495bf6/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
        File "/home/evgnor86/.local/lib/python3.11/site-packages/attrdict/__init__.py", line 5, in <module>
          from attrdict.mapping import AttrMap
        File "/home/evgnor86/.local/lib/python3.11/site-packages/attrdict/mapping.py", line 4, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib64/python3.11/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by maxgerhardt** [comment] 2023-01-30 13:07
Also got this on Ubuntu. Seems to be the same as https://github.com/wxWidgets/Phoenix/issues/2236, i.e.,
```
pip uninstall attrdict
pip install attrdict3
```

**Comment by swt2c** [comment] 2023-01-30 14:09
Duplicate of #2236.

**Closed by swt2c** 2023-01-30 14:09 UTC
